
## Error 30: An exception process cannot be declared inside another exception process...
			



<a name="NOTE1"></a>
<a name="NOTE1_1"></a>


## Reason
<a name="reason_ELTTEXTE000082"></a>
The current process uses an exception process. A new management of exceptions is implemented in this exception process. The exceptions cannot be managed in an exception process.

<a name="NOTE2"></a>
<a name="NOTE2_1"></a>


## Tip
<a name="tip_ELTTEXTE000106"></a>
The code for exception process must be checked with great care. Indeed, if this code contains an error, this error will not be intercepted by an exception process. 

<a name="NOTE3"></a>
<a name="NOTE3_1"></a>


## Examples
<a name="examples_ELTTEXTE000130"></a>


### An exception process is used to manage an error that occurred in the first exception process
<a name="exception_process_used_manage_error_that_occurred_the_first_exception_process_ELTPARAGRAPHE000025"></a>

**Code triggering the error**


```wl
IF InTestMode() = False THEN
	WHEN EXCEPTION
	Error("Error:" + ExceptionInfo(errMessage) + " Code " + ExceptionInfo(errCODE) + ...
			 " at line " + ExceptionInfo(errLINE) + " of "  + ...
			  ExceptionInfo(errProcess) , "EXC")
		WHEN EXCEPTION
			// If we cannot write into .ini, exit from the program
			EndProgram() 
		END
		// Procedure used to write into an INI file
		bWriteIntoIni("")
	END
END
```


**Possible correction**

Delete the extra exception process and check the exception process.


```wl
IF InTestMode() = False THEN
	WHEN EXCEPTION
	Error("Error:" + ExceptionInfo(errMessage) + " Code " + ExceptionInfo(errCODE) + ...
			 " at line " + ExceptionInfo(errLINE) + " of "  + ...
			  ExceptionInfo(errProcess) , "EXC")
		// Procedure used to write into an INI file
		bWriteIntoIni("")
	END
END
```



