
## Error 30: Una excepción Process no puede ser declarada dentro de otra excepción Process...
			



<a name="NOTE1"></a>
<a name="NOTE1_1"></a>


## Motivo
<a name="motivo_ELTTEXTE000082"></a>
El actual Process utiliza una excepción Process. Una nueva gestión de excepciones se implementa en esta excepción Process. Las excepciones no pueden ser manejadas en una excepción Process.

<a name="NOTE2"></a>
<a name="NOTE2_1"></a>


## Consejo
<a name="consejo_ELTTEXTE000106"></a>
El código de la excepción Process debe ser revisado con mucho cuidado.. De hecho, si este código contiene un error, este error no será interceptado por una excepción Process. 

<a name="NOTE3"></a>
<a name="NOTE3_1"></a>


## Ejemplos
<a name="ejemplos_ELTTEXTE000130"></a>


### Una excepción Process se utiliza para gestionar un error que se produjo en la primera excepción Process
<a name="una_excepcion_process_utiliza_para_gestionar_error_que_produjo_primera_excepcion_process_ELTPARAGRAPHE000025"></a>

**Código que desencadena el error**


```wl
IF InTestMode() = False THEN
	WHEN EXCEPTION
	Error("Error:" + ExceptionInfo(errMessage) + " Code " + ExceptionInfo(errCODE) + ...
			 " at line " + ExceptionInfo(errLINE) + " of "  + ...
			  ExceptionInfo(errProcess) , "EXC")
		WHEN EXCEPTION
			// If we cannot write into .ini, exit from the program
			EndProgram() 
		END
		// Procedure used to write into an INI file
		bWriteIntoIni("")
	END
END
```


**Posible corrección**

Borre la excepción extra Process y compruebe la excepción Process.


```wl
IF InTestMode() = False THEN
	WHEN EXCEPTION
	Error("Error:" + ExceptionInfo(errMessage) + " Code " + ExceptionInfo(errCODE) + ...
			 " at line " + ExceptionInfo(errLINE) + " of "  + ...
			  ExceptionInfo(errProcess) , "EXC")
		// Procedure used to write into an INI file
		bWriteIntoIni("")
	END
END
```



